services:
  - type: web
    name: plant-disease-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.6

